-- AlterTable
ALTER TABLE `TravelPhoto` ADD COLUMN `imagePath` VARCHAR(255) NULL,
    ADD COLUMN `imageSize` INTEGER NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `imageData` LONGTEXT NULL;
